# Generated by Django 4.0.5 on 2022-06-17 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('exam_grade', models.CharField(blank=True, max_length=100, null=True)),
                ('exam_date', models.DateTimeField(auto_now=True)),
                ('attempts', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['exam_date'],
            },
        ),
    ]
