# Generated by Django 4.0.5 on 2022-06-20 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
        ('course', '0002_alter_course_exams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='exams',
        ),
        migrations.AddField(
            model_name='course',
            name='exams',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.exam'),
        ),
    ]
