# Generated by Django 4.0.5 on 2022-07-05 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_courses_alter_student_student'),
        ('mytodo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mytodo',
            name='student',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mytodo', to='student.student'),
        ),
    ]
