# Generated by Django 4.0.5 on 2022-06-27 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_course_students_alter_course_exams'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0004_alter_student_courses_alter_student_exams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='course.course'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
